name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.13"
            toxenv: pre-commit
          - python-version: "3.9"
            toxenv: min
          - python-version: "3.9"
            toxenv: min-all
          - python-version: "3.9"
          - python-version: "3.10"
          - python-version: "3.11"
          - python-version: "3.12"
          - python-version: "3.13"
            toxenv: all
          - python-version: "3.13"
            toxenv: scripts
          - python-version: "3.12"  # Keep in sync with tox.ini
            toxenv: docs
          - python-version: "3.13"
            toxenv: twinecheck
          - python-version: "3.13"
            toxenv: py
            timezone: "Pacific/Auckland"
          - python-version: "3.13"
            toxenv: py
            timezone: "Pacific/Fiji"
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install language-pack-fr
        run: sudo apt-get update && sudo apt-get install -y language-pack-fr build-essential
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: |
          TZ=${{ matrix.timezone || 'UTC' }} echo "Running tests with timezone: $TZ"
          TZ=${{ matrix.timezone || 'UTC' }} date
          TZ=${{ matrix.timezone || 'UTC' }} python -c "import datetime; print(f'Python datetime now: {datetime.datetime.now()}')"
          TZ=${{ matrix.timezone || 'UTC' }} python -c "import time; print(f'Python time localtime: {time.localtime()}')"
          TZ=${{ matrix.timezone || 'UTC' }} tox -e ${{ matrix.toxenv || 'py' }}
      - name: Upload coverage.xml to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
